services:
  postgres-dev:
    image: postgres:latest
    container_name: postgres-dev
    ports:
      - "6543:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_DB: ${DEV_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: