# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build, Analyze and Deploy JAR app to Azure Web App - Back-Medicalturns

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build, Analyze and Package
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout
    steps:
      - uses: actions/checkout@v4

      # Configurar JDK 17
      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Cache de SonarQube
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Cache de Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Analizar con SonarQube
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ECIBienestar_diamante-medicalturns-service

      # Construir el artefacto JAR
      - name: Build with Maven
        run: mvn clean install

      # Subir artefacto para el despliegue
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-analyze # Este job depende del éxito del job anterior
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for requesting JWT
      contents: read # Required for actions/checkout
    steps:
      # Descargar artefacto desde el job de build
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      # Iniciar sesión en Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_14D5DEE01A254DB4817EC1AF9B6EC192 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B387C62232B41D3AA8CBE531A92199B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1846C5313CAC4855AFBE5922C30EC9BF }}

      # Desplegar a Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Back-Medicalturns'
          slot-name: 'Production'
          package: '*.jar'
